// Generated by gencpp from file dbw_mkz_msgs/DriverAssistReport.msg
// DO NOT EDIT!


#ifndef DBW_MKZ_MSGS_MESSAGE_DRIVERASSISTREPORT_H
#define DBW_MKZ_MSGS_MESSAGE_DRIVERASSISTREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dbw_mkz_msgs
{
template <class ContainerAllocator>
struct DriverAssistReport_
{
  typedef DriverAssistReport_<ContainerAllocator> Type;

  DriverAssistReport_()
    : header()
    , decel(0.0)
    , decel_src(0)
    , fcw_enabled(false)
    , fcw_active(false)
    , aeb_enabled(false)
    , aeb_precharge(false)
    , aeb_braking(false)
    , acc_enabled(false)
    , acc_braking(false)  {
    }
  DriverAssistReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , decel(0.0)
    , decel_src(0)
    , fcw_enabled(false)
    , fcw_active(false)
    , aeb_enabled(false)
    , aeb_precharge(false)
    , aeb_braking(false)
    , acc_enabled(false)
    , acc_braking(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _decel_type;
  _decel_type decel;

   typedef uint8_t _decel_src_type;
  _decel_src_type decel_src;

   typedef uint8_t _fcw_enabled_type;
  _fcw_enabled_type fcw_enabled;

   typedef uint8_t _fcw_active_type;
  _fcw_active_type fcw_active;

   typedef uint8_t _aeb_enabled_type;
  _aeb_enabled_type aeb_enabled;

   typedef uint8_t _aeb_precharge_type;
  _aeb_precharge_type aeb_precharge;

   typedef uint8_t _aeb_braking_type;
  _aeb_braking_type aeb_braking;

   typedef uint8_t _acc_enabled_type;
  _acc_enabled_type acc_enabled;

   typedef uint8_t _acc_braking_type;
  _acc_braking_type acc_braking;



  enum {
    DECEL_NONE = 0u,
    DECEL_AEB = 1u,
    DECEL_ACC = 2u,
  };


  typedef boost::shared_ptr< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> const> ConstPtr;

}; // struct DriverAssistReport_

typedef ::dbw_mkz_msgs::DriverAssistReport_<std::allocator<void> > DriverAssistReport;

typedef boost::shared_ptr< ::dbw_mkz_msgs::DriverAssistReport > DriverAssistReportPtr;
typedef boost::shared_ptr< ::dbw_mkz_msgs::DriverAssistReport const> DriverAssistReportConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dbw_mkz_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dbw_mkz_msgs': ['/home/weiyang/hybrid_rrt_planning/src/dbw_mkz_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97f55d54ac7adaf52a6882520c5247ff";
  }

  static const char* value(const ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97f55d54ac7adaf5ULL;
  static const uint64_t static_value2 = 0x2a6882520c5247ffULL;
};

template<class ContainerAllocator>
struct DataType< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbw_mkz_msgs/DriverAssistReport";
  }

  static const char* value(const ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
# Vehicle Decceleration (m/s^2)\n\
float32 decel\n\
\n\
# Deceleration source\n\
uint8 decel_src\n\
uint8 DECEL_NONE=0\n\
uint8 DECEL_AEB=1\n\
uint8 DECEL_ACC=2\n\
\n\
# FCW Status\n\
bool fcw_enabled\n\
bool fcw_active\n\
\n\
# AEB Status\n\
bool aeb_enabled\n\
bool aeb_precharge\n\
bool aeb_braking\n\
\n\
# ACC Status\n\
bool acc_enabled\n\
bool acc_braking\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.decel);
      stream.next(m.decel_src);
      stream.next(m.fcw_enabled);
      stream.next(m.fcw_active);
      stream.next(m.aeb_enabled);
      stream.next(m.aeb_precharge);
      stream.next(m.aeb_braking);
      stream.next(m.acc_enabled);
      stream.next(m.acc_braking);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriverAssistReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dbw_mkz_msgs::DriverAssistReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "decel: ";
    Printer<float>::stream(s, indent + "  ", v.decel);
    s << indent << "decel_src: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.decel_src);
    s << indent << "fcw_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fcw_enabled);
    s << indent << "fcw_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fcw_active);
    s << indent << "aeb_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aeb_enabled);
    s << indent << "aeb_precharge: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aeb_precharge);
    s << indent << "aeb_braking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.aeb_braking);
    s << indent << "acc_enabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acc_enabled);
    s << indent << "acc_braking: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.acc_braking);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DBW_MKZ_MSGS_MESSAGE_DRIVERASSISTREPORT_H
