// Generated by gencpp from file dbw_mkz_msgs/QualityFactor.msg
// DO NOT EDIT!


#ifndef DBW_MKZ_MSGS_MESSAGE_QUALITYFACTOR_H
#define DBW_MKZ_MSGS_MESSAGE_QUALITYFACTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dbw_mkz_msgs
{
template <class ContainerAllocator>
struct QualityFactor_
{
  typedef QualityFactor_<ContainerAllocator> Type;

  QualityFactor_()
    : value(0)  {
    }
  QualityFactor_(const ContainerAllocator& _alloc)
    : value(0)  {
  (void)_alloc;
    }



   typedef uint8_t _value_type;
  _value_type value;



  enum {
    OK = 0u,
    EMPTY = 1u,
    CORRUPT = 2u,
    FAULT = 3u,
  };


  typedef boost::shared_ptr< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> const> ConstPtr;

}; // struct QualityFactor_

typedef ::dbw_mkz_msgs::QualityFactor_<std::allocator<void> > QualityFactor;

typedef boost::shared_ptr< ::dbw_mkz_msgs::QualityFactor > QualityFactorPtr;
typedef boost::shared_ptr< ::dbw_mkz_msgs::QualityFactor const> QualityFactorConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dbw_mkz_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'dbw_mkz_msgs': ['/home/weiyang/hybrid_rrt_planning/src/dbw_mkz_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e016f2e62eedbf749ab8c93a8c2f786f";
  }

  static const char* value(const ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe016f2e62eedbf74ULL;
  static const uint64_t static_value2 = 0x9ab8c93a8c2f786fULL;
};

template<class ContainerAllocator>
struct DataType< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbw_mkz_msgs/QualityFactor";
  }

  static const char* value(const ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 value\n\
\n\
uint8 OK=0\n\
uint8 EMPTY=1\n\
uint8 CORRUPT=2\n\
uint8 FAULT=3\n\
";
  }

  static const char* value(const ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QualityFactor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dbw_mkz_msgs::QualityFactor_<ContainerAllocator>& v)
  {
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DBW_MKZ_MSGS_MESSAGE_QUALITYFACTOR_H
