// Generated by gencpp from file hybrid_rrt/path_point.msg
// DO NOT EDIT!


#ifndef HYBRID_RRT_MESSAGE_PATH_POINT_H
#define HYBRID_RRT_MESSAGE_PATH_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hybrid_rrt
{
template <class ContainerAllocator>
struct path_point_
{
  typedef path_point_<ContainerAllocator> Type;

  path_point_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , dir(0)  {
    }
  path_point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , dir(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef int32_t _dir_type;
  _dir_type dir;





  typedef boost::shared_ptr< ::hybrid_rrt::path_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_rrt::path_point_<ContainerAllocator> const> ConstPtr;

}; // struct path_point_

typedef ::hybrid_rrt::path_point_<std::allocator<void> > path_point;

typedef boost::shared_ptr< ::hybrid_rrt::path_point > path_pointPtr;
typedef boost::shared_ptr< ::hybrid_rrt::path_point const> path_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_rrt::path_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_rrt::path_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hybrid_rrt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hybrid_rrt': ['/home/weiyang/hybrid_rrt_planning/src/hybrid_rrt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_rrt::path_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_rrt::path_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_rrt::path_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_rrt::path_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_rrt::path_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_rrt::path_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_rrt::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb915744e92a8a80ee68cb28baacef20";
  }

  static const char* value(const ::hybrid_rrt::path_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb915744e92a8a80ULL;
  static const uint64_t static_value2 = 0xee68cb28baacef20ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_rrt::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_rrt/path_point";
  }

  static const char* value(const ::hybrid_rrt::path_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_rrt::path_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 yaw\n\
int32 dir\n\
";
  }

  static const char* value(const ::hybrid_rrt::path_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_rrt::path_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.dir);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_rrt::path_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_rrt::path_point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "dir: ";
    Printer<int32_t>::stream(s, indent + "  ", v.dir);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_RRT_MESSAGE_PATH_POINT_H
