// Generated by gencpp from file hybrid_rrt/path_list.msg
// DO NOT EDIT!


#ifndef HYBRID_RRT_MESSAGE_PATH_LIST_H
#define HYBRID_RRT_MESSAGE_PATH_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hybrid_rrt/path_point.h>

namespace hybrid_rrt
{
template <class ContainerAllocator>
struct path_list_
{
  typedef path_list_<ContainerAllocator> Type;

  path_list_()
    : path()  {
    }
  path_list_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::hybrid_rrt::path_point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hybrid_rrt::path_point_<ContainerAllocator> >::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::hybrid_rrt::path_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hybrid_rrt::path_list_<ContainerAllocator> const> ConstPtr;

}; // struct path_list_

typedef ::hybrid_rrt::path_list_<std::allocator<void> > path_list;

typedef boost::shared_ptr< ::hybrid_rrt::path_list > path_listPtr;
typedef boost::shared_ptr< ::hybrid_rrt::path_list const> path_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hybrid_rrt::path_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hybrid_rrt::path_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hybrid_rrt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'hybrid_rrt': ['/home/weiyang/hybrid_rrt_planning/src/hybrid_rrt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_rrt::path_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hybrid_rrt::path_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_rrt::path_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hybrid_rrt::path_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_rrt::path_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hybrid_rrt::path_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hybrid_rrt::path_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11f32201945158a1dde087b80a756425";
  }

  static const char* value(const ::hybrid_rrt::path_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11f32201945158a1ULL;
  static const uint64_t static_value2 = 0xdde087b80a756425ULL;
};

template<class ContainerAllocator>
struct DataType< ::hybrid_rrt::path_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hybrid_rrt/path_list";
  }

  static const char* value(const ::hybrid_rrt::path_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hybrid_rrt::path_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_point[] path\n\
\n\
================================================================================\n\
MSG: hybrid_rrt/path_point\n\
float64 x\n\
float64 y\n\
float64 yaw\n\
int32 dir\n\
";
  }

  static const char* value(const ::hybrid_rrt::path_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hybrid_rrt::path_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hybrid_rrt::path_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hybrid_rrt::path_list_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hybrid_rrt::path_point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HYBRID_RRT_MESSAGE_PATH_LIST_H
